=== jsonmc/jsonmc/schemas/movie.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "person": {
      "type": "string"
    },
    "personArray": {
      "type": "array",
      "minItems": 2,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "personOrPersonArray": {
      "oneOf": [
        { "$ref": "#/definitions/person" },
        { "$ref": "#/definitions/personArray" }
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "year": {
      "type": "integer"
    },
    "runtime": {
      "type": "number"
    },
    "future": {
      "enum": [true]
    },
    "categories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "action",
          "adventure",
          "animation",
          "biography",
          "comedy",
          "comedy-drama",
          "crime",
          "drama",
          "dystopian",
          "family",
          "fantasy",
          "film-noir",
          "history",
          "horror",
          "music",
          "musical",
          "mystery",
          "romance",
          "sci-fi",
          "short",
          "sport",
          "spy",
          "superhero",
          "teen",
          "thriller",
          "western"
        ]
      }
    },
    "release-date": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "director": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "writer": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "actors": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "storyline": {
      "type": "string"
    }
  },
  "required": ["name", "year"],
  "anyOf": [
    { "required": ["runtime"] },
    { "required": ["future"] }
  ]
}

=== jsonmc/jsonmc/movies/1993/addams-family-values.json
{
	"name": "Addams Family Values",
	"year": 1993,
	"runtime": 94,
	"categories": [
	  "comedy",
	  "family"
	],
	"release-date": "1993-11-19",
	"director": "Barry Sonnenfeld",
	"writer": "Paul Rudnick",
	"actors": [
	  "Anjelica Huston",
	  "Raúl Juliá",
	  "Christopher Lloyd",
	  "Christina Ricci",
	  "Joan Cusack"
	],
	"storyline": "The Addams Family try to rescue their beloved uncle Fester from his gold-digging new love, a black widow named Debbie."
  }

=== jsonmc/jsonmc/movies/2007/august-rush.json
{
  "name": "August Rush",
  "year": 2007,
  "runtime": 114,
  "categories": [
    "romance",
    "drama",
    "music"
  ],
  "release-date": "2007-11-21",
  "director": "Kirsten Sheridan",
  "writer": [
    "Nick Castle",
    "James V. Hart"
  ],
  "actors": [
    "Freddie Highmore",
    "Keri Russell",
    "Jonathan Rhys Meyers"
  ],
  "storyline": "A drama with fairy tale elements, where an orphaned musical prodigy uses his gift as a clue to finding his birth parents."
}

=== jsonmc/jsonmc/movies/2017/saw-viii.json
{
  "name": "Saw VIII ",
  "year": 2017,
  "runtime": 92,
  "categories": [
    "horror",
    "mystery",
    "thriller"
  ],
  "release-date": "2017-11-23",
  "director": "Michael Spierig",
  "writer": "Josh Stolberg",
  "actors": [
    "Matt Passmore", 
    "Tobin Bell",
    "Callum Keith Rennie" 
  ]
}

=== jsonmc/jsonmc/movies/2018/christopher-robin.json
{
    "name": "Christopher Robin",
    "year": 2018,
    "runtime": 104,
    "categories": [
      "fantasy",
      "family",
      "animation"
    ],
    "release-date": "2018-07-30",
    "director": "Marc Forster",
    "writer": [
      "Alex Ross Perry",
      "Tom McCarthy",
      "Allison Schroeder",
      "Greg Brooker",
      "Mark Steven Johnson",
      "A.A. Milne",
      "Ernest Shepard"

    ],
    "actors": [
      "Ewan McGregor",
      "Hayley Atwell",
      "Jim Cummings",
      "Brad Garrett"
    ],
    "storyline": "A working-class family man, Christopher Robin, encounters his childhood friend Winnie-the-Pooh, who helps him to rediscover the joys of life."
  }

=== jsonmc/jsonmc/movies/1975/monty-python-and-the-holy-grail.json
{
  "name": "Monty Python and the Holy Grail",
  "year": 1975,
  "runtime": 91,
  "categories": [
    "adventure",
    "comedy",
    "fantasy"
  ],
  "release-date": "1975-05-25",
  "director": [
    "Terry Gilliam",
    "Terry Jones"
  ],
  "writer": [
    "Graham Chapman",
    "John Cleese",
    "Eric Idle",
    "Terry Gilliam",
    "Terry Jones",
    "Michael Palin"
  ],
  "actors": [
    "Graham Chapman",
    "John Cleese",
    "Eric Idle"
  ]
}

=== jsonmc/jsonmc/movies/2016/jason-bourne.json
{
    "name": "Jason Bourne",
    "year": 2016,
    "runtime": 123,
    "categories": [
      "action",
      "thriller"
    ],
    "release-date": "2016-04-14",
    "director": "Paul Greengrass",
    "writer": [
      "Paul Greengrass",
      "Christopher Rouse"
    ],
    "actors": [
        "Matt Damon", 
        "Tommy Lee Jones", 
        "Alicia Vikander" 
    ],
    "storyline": "The CIA's most dangerous former operative is drawn out of hiding to uncover more explosive truths about his past. "
  }

=== jsonmc/jsonmc/movies/1984/the-last-starfighter.json
{
  "name": "The Last Starfighter",
  "year": 1984,
  "runtime": 101,
  "categories": [
    "sci-fi"
  ],
  "release-date": "1984-07-13",
  "director": "Nick Castle",
  "writer": [
    "Jonathan Betuel"
  ],
  "actors": [
    "Lance Guest",
    "Robert Preston",
    "Catherine Mary Stewart",
    "Dan O'Herlihy"
  ],
  "storyline": "After getting the high score on his favorite arcade game in the trailer park, Alex Rogan is taken away on the space ride of his life to fight evil where the game is real."
}

=== jsonmc/jsonmc/movies/2018/love-simon.json
{
	"name": "Love, Simon",
	"year": 2018,
	"runtime": 110,
	"categories": [
		"romance",
		"comedy",
		"drama"
	],
	"release-date": "2018-03-16",
	"director": "Greg Belanti",
	"writer": [
		"Isaac Aptaker",
		"Elizabeth Berger"
	],
	"actors": [
		"Nick Robinson",
		"Josh Duhamel",
		"Jennifer Garner",
		"Katherine Langford"
	],
	"storyline": "Everyone deserves a great love story, but for 17-year-old Simon Spier, it's a little more complicated. He hasn't told his family or friends that he's gay, and he doesn't know the identity of the anonymous classmate that he's fallen for online. Resolving both issues proves hilarious, terrifying and life-changing."
}
