=== jsonmc/jsonmc/schemas/movie.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "person": {
      "type": "string"
    },
    "personArray": {
      "type": "array",
      "minItems": 2,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "personOrPersonArray": {
      "oneOf": [
        { "$ref": "#/definitions/person" },
        { "$ref": "#/definitions/personArray" }
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "year": {
      "type": "integer"
    },
    "runtime": {
      "type": "number"
    },
    "future": {
      "enum": [true]
    },
    "categories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "action",
          "adventure",
          "animation",
          "biography",
          "comedy",
          "comedy-drama",
          "crime",
          "drama",
          "dystopian",
          "family",
          "fantasy",
          "film-noir",
          "history",
          "horror",
          "music",
          "musical",
          "mystery",
          "romance",
          "sci-fi",
          "short",
          "sport",
          "spy",
          "superhero",
          "teen",
          "thriller",
          "western"
        ]
      }
    },
    "release-date": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "director": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "writer": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "actors": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "storyline": {
      "type": "string"
    }
  },
  "required": ["name", "year"],
  "anyOf": [
    { "required": ["runtime"] },
    { "required": ["future"] }
  ]
}

=== jsonmc/jsonmc/movies/2018/paskal.json
{
  "name": "PASKAL",
  "year": 2018,
  "runtime": 115,
  "categories": [
    "action",
    "drama"
  ],
  "release-date": "2018-09-27",
  "director": "Adrian Teh",
  "writer": [
    "Anwari Ashraf",
    "Chee Ang Keoh",
    "Frank See",
    "Adrian Teh"
  ],
  "actors": [
    "Adi Afendi",
    "Ammar Alfian",
    "Hairul Azreen"
  ],
  "storyline": "PASKAL, or Pasukan Khas Laut, is an elite unit in the Royal Malaysian Navy. The movie follows the true events of PASKAL's Lieutenant Commander Arman Anwar and his team's mission to rescue a tanker, MV Bunga Laurel, that was hijacked by Somalian Pirates in 2011."
}

=== jsonmc/jsonmc/movies/2017/john-wick-chapter-2.json
{
  "name": "John Wick: Chapter 2",
  "year": 2017,
  "runtime": 122,
  "categories": [
    "action",
    "crime",
    "thriller"
  ],
  "release-date": "2017-02-10",
  "director": "Chad Stahelski",
  "writer": [
    "Derek Kolstad"
  ],
  "actors": [
    "Keanu Reeves",
    "Claudia Gerini",
    "Laurence Fishburne",
    "Ruby Rose"
  ],
  "storyline": "After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life."
}

=== jsonmc/jsonmc/movies/2003/x-men-2.json
{
  "name": "X-Men 2",
  "year": 2003,
  "runtime": 134,
  "categories": [
    "action",
    "adventure",
    "fantasy"
  ],
  "release-date": "2003-05-02",
  "director": "Bryan Singer",
  "writer": [
    "Zak Penn",
    "David Hayter",
    "Bryan Singer",
    "Michael Dougherty",
    "Dan Harris"
  ],
  "actors": [
    "Patrick Stewart",
    "Hugh Jackman",
    "Halle Berry"
  ],
  "storyline": "The X-Men band together to find a mutant assassin who has made an attempt on the President's life, while the Mutant Academy is attacked by military forces."
}

=== jsonmc/jsonmc/movies/2017/war-of-the-planet-of-the-apes.json
{
  "name": "War of The Planet Of The Apes",
  "year": 2017,
  "runtime": 140,
  "categories": [
    "action",
    "sci-fi",
    "thriller",
    "drama",
    "adventure"
  ],
  "release-date": "2017-07-10",
  "director": "Matt Reeves",
  "writer": [
    "Mark Bomback",
    "Matt Reeves"
  ],
  "actors": [
    "Andy Serkes",
    "Woody harrelson",
    "Steve Zahn",
    "Karin Konoval",
    "Amiah Miller"
  ],
  "storyline": "Caesar and his apes are forced into a deadly conflict with an army of humans led by a ruthless Colonel. After the apes suffer unimaginable losses, Caesar wrestles with his darker instincts and begins his own mythic quest to avenge his kind. As the journey finally brings them face to face, Caesar and the Colonel are pitted against each other in an epic battle that will determine the fate of both their species and the future of the planet."
}

=== jsonmc/jsonmc/movies/2000/the-road-to-el-dorado.json
{
  "name": "The Road to El Dorado",
  "year": 2000,
  "runtime": 89,
  "categories": [
    "animation",
    "adventure",
    "comedy"
  ],
  "release-date": "2000-03-31",
  "director": [
	"Bibo Bergeron",
	"Don Paul",
	"Jeffrey Katzenberg"
  ],
  "writer": [
    "Terry Rossio",
    "Ted Elliott",
    "Karey Kirkpatrick"
  ],
  "actors": [
    "Kevin Kline",
    "Kenneth Branagh",
    "Rosie Perez",
	"Armand Assante",
	"Edward James Olmos",
	"Jim Cummings"
  ],
  "storyline": "Two swindlers get their hands on a map to the fabled city of gold, El Dorado."
}

=== jsonmc/jsonmc/movies/2013/fast-and-furious-6.json
{
  "name": "Fast & Furious 6",
  "year": 2013,
  "runtime": 130,
  "categories": [
    "action",
    "crime",
    "thriller"
  ],
  "release-date": "2013-05-24",
  "director": "Justin Lin",
  "writer": [
    "Chris Morgan"
  ],
  "actors": [
    "Vin Diesel",
    "Paul Walker",
    "Dwayne Johnson",
    "Michelle Rodriguez",
    "Jordana Brewster",
    "Tyrese Gibson",
    "Chris Ludacris Bridges",
    "Sung Kang",
    "Luke Evans",
    "Gina Carano",
    "John Ortiz"
  ],
  "storyline": "Agent Hobbs cuts a deal with Dominic to clear his crew's all criminal records and in return catch a team of mercenaries. During the journey, Dominic unexpectedly meets his presumed-dead lover Letty who is a part of the group."
}

=== jsonmc/jsonmc/movies/2001/harry-potter-and-the-sorcerers-stone.json
{
  "name": "Harry Potter and the Sorcerer's Stone",
  "year": 2001,
  "runtime": 152,
  "categories": [
    "adventure",
    "family",
    "fantasy"
  ],
  "release-date": "2001-11-16",
  "director": "Chris Columbus",
  "writer": [
    "J.K. Rowling",
    "Steve Kloves"
  ],
  "actors": [
    "Daniel Radcliffe",
    "Rupert Grint",
    "Richard Harris"
  ],
  "storyline": "At Hogwarts School of Witchcraft and Wizardry, Harry embarks on the adventure of a lifetime. He learns the high-flying sport Quidditch and plays a thrilling game with living chess pieces on his way to face a Dark Wizard bent on destroying him."
}

=== jsonmc/jsonmc/movies/2017/kong-skull-island.json
{
    "name": "Kong: Skull Island",
    "year": 2017,
    "runtime": 118,
    "categories": [
      "thriller",
      "mystery"
    ],
    "release-date": "2017-03-10",
    "director": "Jordan Vogt-Roberts",
    "writer": [
      "Dan Gilroy",
      "Max Borenstein",
      "Derek Connolly",
      "John Gatins"
    ],
    "actors": [
      "Tom Hiddleston",
      "Samuel L. Jackson",
      "Brie Larson",
      "John C. Reilly"
    ],
    "storyline": "A washed up monster chaser convinces the U.S. Government to fund a trip to an unexplored island in the South Pacific. Under the guise of geological research, the team travels to Skull Island."
  }
