=== jsonmc/jsonmc/schemas/movie.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "person": {
      "type": "string"
    },
    "personArray": {
      "type": "array",
      "minItems": 2,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "personOrPersonArray": {
      "oneOf": [
        { "$ref": "#/definitions/person" },
        { "$ref": "#/definitions/personArray" }
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "year": {
      "type": "integer"
    },
    "runtime": {
      "type": "number"
    },
    "future": {
      "enum": [true]
    },
    "categories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "action",
          "adventure",
          "animation",
          "biography",
          "comedy",
          "comedy-drama",
          "crime",
          "drama",
          "dystopian",
          "family",
          "fantasy",
          "film-noir",
          "history",
          "horror",
          "music",
          "musical",
          "mystery",
          "romance",
          "sci-fi",
          "short",
          "sport",
          "spy",
          "superhero",
          "teen",
          "thriller",
          "western"
        ]
      }
    },
    "release-date": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "director": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "writer": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "actors": {
      "$ref": "#/definitions/personOrPersonArray"
    },
    "storyline": {
      "type": "string"
    }
  },
  "required": ["name", "year"],
  "anyOf": [
    { "required": ["runtime"] },
    { "required": ["future"] }
  ]
}

=== jsonmc/jsonmc/movies/2007/juno.json
{
  "name": "Juno",
  "year": 2007,
  "runtime": 96,
  "categories": [
    "comedy",
    "teen"
  ],
  "release-date": "2007-09-01",
  "director": "Jason Reitman",
  "writer": [
    "Diablo Cody"
  ],
  "actors": [
    "Ellen Page",
    "Michael Cera",
    "Jennifer Garner",
    "Jason Bateman",
    "Allison Janney",
    "J. K. Simmons"
  ],
  "storyline": "Sixteen-year-old Minnesota high-schooler Juno MacGuff discovers she is pregnant by her friend and longtime admirer, Paulie Bleeker."
}

=== jsonmc/jsonmc/movies/1970/the-aristocats.json
{
  "name": "The Aristocats",
  "year": 1970,
  "runtime": 78,
  "categories": [
    "animation",
    "adventure",
    "comedy"
  ],
  "release-date": "1970-12-11",
  "director": "Wolfgang Reitherman",
  "writer": [
    "Ken Anderson",
    "Larry Clemmons",
    "Eric Cleworth",
    "Vance Garry",
    "Julius Svendsen",
    "Frank Thomas",
    "Ralph Wright"
  ],
  "actors": [
    "Phil Harris",
    "Eva Gabor",
    "Hermione Baddeley",
    "Gary Dubin",
    "Dean Clark",
    "Sterling Holloway",
    "Roddy Maude-Roxby",
    "Liz English"
  ],
  "storyline": "With the help of a smooth talking tomcat, a family of Parisian felines set to inherit a fortune from their owner try to make it back home after a jealous butler kidnaps them and leaves them in the country."
}

=== jsonmc/jsonmc/movies/2017/guardians-of-the-galaxy-vol-2.json
{
  "name": "Guardians of the Galaxy Vol. 2",
  "year": 2017,
  "runtime": 137,
  "categories": [
    "action",
    "sci-fi",
    "comedy",
    "adventure"
  ],
  "release-date": "2017-04-19",
  "director": "James Gunn",
  "writer": [
    "James Gunn"
  ],
  "actors": [
    "Chris Pratt",
    "Zoe Saldana",
    "Dave Bautista",
    "Vin Diesel",
    "Bradley Cooper",
    "Michael Rooker",
    "Karen Gillan",
    "Pom Klementieff",
    "Sean Gunn",
    "Sylvester Stallone"
  ],
  "storyline": "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage."
}

=== jsonmc/jsonmc/movies/2018/22-july.json
{
  "name": "22 July",
  "year": 2018,
  "runtime": 143,
  "categories": [
    "crime",
    "drama",
    "history"
  ],
  "release-date": "2018-10-10",
  "director": "Paul Greengrass",
  "writer": [
    "Paul Greengrass",
    "Åsne Seierstad"
  ],
  "actors": [
    "Anders Danielsen Lie",
    "Jonas Strand Gravli",
    "Jon Øigarden"
  ],
  "storyline": "In Norway on 22 July 2011, right-wing terrorist Anders Behring Breivik murdered 77 young people attending a Labour Party Youth Camp on Utøya Island outside of Oslo. A three-part story. About the survivors of the attacks, the political leadership of Norway, and the lawyers involved."
}

=== jsonmc/jsonmc/movies/2010/the-other-guys.json
{
  "name": "The Other Guys",
  "year": 2010,
  "runtime": 107,
  "categories": [
    "action",
    "comedy",
    "crime"
  ],
  "release-date": "2010-08-06",
  "director": "Adam McKay",
  "writer": [
    "Adam McKay",
    "Chris Henchy"
  ],
  "actors": [
    "Will Ferrell",
    "Mark Wahlberg",
    "Derek Jeter"
  ],
  "storyline": "Two mismatched New York City detectives seize an opportunity to step up like the city's top cops, whom they idolize, only things don't quite go as planned."
}

=== jsonmc/jsonmc/movies/1998/kuch-kuch-hota-hai.json
{
    "name": "Kuch Kuch Hota Hai",
    "year": 1998,
    "runtime": 177,
    "categories": [
      "comedy",
      "drama",
      "musical"
    ],
    "release-date": "1998-10-16",
    "director": "Karan Johar",
    "writer": [
      "Karan Johar",
      "Karan Johar"
    ],
    "actors": [
        "Shah Rukh Khan", "Kajol", "Rani Mukerji"
    ],
    "storyline": "During their college years, Anjali was in love with her best-friend Rahul, but he had eyes only for Tina. Years later, Rahul and the now-deceased Tina's eight-year-old daughter attempts to reunite her father and Anjali."
  }

=== jsonmc/jsonmc/movies/1996/bio-dome.json
{
    "name": "Bio-Dome",
    "year": 1996,
    "runtime": 88,
    "categories": [
      "comedy"
    ],
    "release-date": "1996-01-12",
    "director": "Jason Bloom",
    "writer": [
      "Adam Leff",
      "Mitchell Peck",
      "Jason Blumenthal",
      "Kip Koenig",
      "Scott Marcano"
    ],
    "actors": [
      "Pauly Shore",
      "Stephen Baldwin",
      "William Atherton",
      "Joey Adams"
    ],
    "storyline": "Bud and Doyle are here to save the world. But who's gonna save the world from Bud and Doyle?"
}

=== jsonmc/jsonmc/movies/2018/ana-e-vitoria.json
{
  "name": "Ana e Vit처ria",
  "year": 2018,
  "runtime": 115,
  "categories": [
    "biography",
    "comedy",
    "music"
  ],
  "release-date": "2018-08-02",
  "director": "Matheus Souza",
  "writer": [
    "Matheus Souza"
  ],
  "actors": [
    "Ana Caetano",
    "Vit처ria Falc찾o",
    "Clarissa M체ller",
    "Thati Lopes"
  ],
  "storyline": "Two girls have a chance encounter and instantly befriend. While trying to find themselves, they decide to pursue music together."
}
